mqtt_communication:
  ros__parameters:
    input_endpoint: "an2dks8wwmmxc-ats.iot.us-east-1.amazonaws.com"
    input_port: 8883
    input_cert: "/home/pi/workspace/ControlTower/src/ct_package/ct_package/connect_device/mqtt-oc.cert.pem"
    input_key: "/home/pi/workspace/ControlTower/src/ct_package/ct_package/connect_device/mqtt-oc.private.key"
    input_ca: "/home/pi/workspace/ControlTower/src/ct_package/ct_package/connect_device/root-CA.crt"
    input_clientId: "ControlTower"
    trash_info_topic: "robot/trash"
    robot_log_topic: "robot/log"
    input_count: 10
    input_proxy_host: ""
    input_proxy_port: 0
    input_is_ci: false